---

- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
    update_cache: yes
    state: present

- name: Install docker requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
    - docker-engine=1.12.4-0~ubuntu-xenial
    - python-dev
    - python-pip

- name: Install Docker-py
  pip:
    name: docker-py
    state: present

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true
